---
# tasks file for blog
- name: Git clone blog repo on HEAD
  ansible.builtin.git:
    repo: "{{ blog_repo_url }}"
    dest: "{{ blog_clone_repo }}"

- name: Create DB_PASSWORD secret
  shell:
    set -o errexit
    set -o pipefail
    set -o nounset

      kubectl create secret generic blog-secrets --from-env-file="{{ path_to_secret_env }}"
      
    exit 0
  run_once: False
  changed_when: False
  register: result
  args:
    executable: "/bin/bash"

- name: Deploy blog chart from local path
  kubernetes.core.helm:
    name: "{{ blog_release_name }}"
    chart_ref: "{{ blog_clone_repo }}"
    release_namespace:  "{{ blog_namespace }}"
    create_namespace: true
    wait: yes
    # values:  "{{ lookup('template', 'templates/values.yaml') | from_yaml }}"

- name: Clean up cloned repository
  file:
    path: "{{ blog_clone_repo }}"
    state: absent