replicas: 1

ingress:
  enabled: true
  annotations: {
    prometheus.io/scrape: 'true',
    kubernetes.io/ingress.class: nginx,
    nginx.ingress.kubernetes.io/ssl-redirect: "true",
    cert-manager.io/cluster-issuer: "{{ letsencrypt }}",
  }

  path: /

  hosts:
    - "{{ grafana_dns }}"
    
  tls:
    - secretName: "{{ secret_name }}"
      hosts:
        - "{{ grafana_dns }}"