---
# tasks file for prometheus

- name: Add prometheus repo
  kubernetes.core.helm_repository:
    name:  "{{ prometheus_repo_name }}"
    repo_url:  "{{ prometheus_chart_url }}"

- name: Deploy prometheus
  block:
    - name: Deploy prometheus
      kubernetes.core.helm:
        name: "{{ prometheus_release_name }}"
        chart_ref: "{{ prometheus_chart_name }}"
        release_namespace: "{{ prometheus_namespace }}"
        create_namespace: true
        values:  "{{ lookup('template', 'templates/values.yaml') | from_yaml }}"
        wait: yes
      register: result
  rescue:
    - name: print find_results
      debug:
        msg: "{{ result }}"